[tool.mypy]
ignore_missing_imports = true

[tool.ruff.lint]
ignore = ["ANN", "CPY", "D", "E501", "FBT003", "N801", "N999", "PLR2004", "PLR0916"]
preview = true
select = ["ALL"]

[tool.ruff.lint.mccabe]
max-complexity = 11
